# Generated by Django 4.0.4 on 2022-04-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_song_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.CharField(default='', max_length=255),
        ),
    ]
